### ISSUE TITLE
RTSP seems not so stable, got to manual reset the esp32 cam  

### ISSUE THREAD

**Issue by soovui** [circuitrocks/ESP32-RTSP#2]
Hi,

I try to put it up and running yesterday night, it stops working and got to manually reset it.  I actually try a few RTSP program from others, it is the same.  Even I change power supply too.  Can you help to look into it?

Stuart

**Comment by beegee-tokyo** [comment]
Difficult to say, I have mine online for days now without the need to reset it.

One problem I found is that if both Webserver and RTSP server are enabled, the streaming is either very slow or stops sometimes.

In **`main.h`** check the following lines to make sure only one of the two is enabled:
```cpp
// Select which of the servers are active
// Select only one or the streaming will be very slow!
// #define ENABLE_WEBSERVER
#define ENABLE_RTSPSERVER
```

Other than that, my module is really sensitive to power problems. I had to try several USB cables before I got it to run. Right now I am using a USB cable that is made for charging only, it does not have data lines and that works best for me.

**Comment by soovui** [comment]
> Difficult to say, I have mine online for days now without the need to reset it.
> 
> One problem I found is that if both Webserver and RTSP server are enabled, the streaming is either very slow or stops sometimes.
> 
> In **`main.h`** check the following lines to make sure only one of the two is enabled:
> 
> ```c++
> // Select which of the servers are active
> // Select only one or the streaming will be very slow!
> // #define ENABLE_WEBSERVER
> #define ENABLE_RTSPSERVER
> ```
> 
> Other than that, my module is really sensitive to power problems. I had to try several USB cables before I got it to run. Right now I am using a USB cable that is made for charging only, it does not have data lines and that works best for me.

Yes I only enable RTSP and I am using purely 5v 3000mA DC power adapter.  Unfortunately, I tested this morning ok but at night I got to reset it again to make it work.

**Comment by beegee-tokyo** [comment]
Your setup sounds good. I have no idea why it stops after a few hours.

Can you try on a different WiFi network? Just to eliminate the possibility of a router problem?

**Comment by beegee-tokyo** [comment]
Please report problem at [Micro-RTSP](https://github.com/geeksville/Micro-RTSP). I wrote just the app, not the streaming library.
