### ISSUE TITLE
vlc streaming closes after about 10mins

### ISSUE THREAD

**Issue by dpunkz09** [circuitrocks/ESP32-RTSP#5]
13:08:17.360 -> error sending udp packet
13:08:17.408 -> error sending udp packet
13:08:17.408 -> error sending udp packet
13:08:17.408 -> error sending udp packet
13:08:17.455 -> error sending udp packet
13:08:17.455 -> error sending udp packet
13:08:17.455 -> error sending udp packet
13:08:17.502 -> error sending udp packet
13:08:18.528 -> RTSP received TEARDOWN
13:08:18.528 -> RTSP client closed connection
13:08:18.528 -> closing TCP socket
13:08:18.528 -> closing UDP socket
13:08:18.528 -> closing UDP socket

**Comment by beegee-tokyo** [comment]
Please report problem at [Micro-RTSP](https://github.com/geeksville/Micro-RTSP). I wrote just the app, not the streaming library.
