### ISSUE TITLE
HTTP vs RTSP

### ISSUE THREAD

**Issue by thomas725** [circuitrocks/ESP32-RTSP#6]
Hey there!

I stumbled upon your blog post https://learn.circuit.rocks/esp32-cam-with-rtsp-video-streaming and from there on to your repository here.

I was wondering if you could share your experience which of the two server options you included (HTTP vs RTSP)
-) has better performance (higher fps)
-) takes less space in the code binary upload to the esp32

Thank you for sharing your code and experience :)

**Comment by beegee-tokyo** [comment]
Sorry for the late reply.

I cannot tell you. After initial test of RTSP and HTTP I setup my camera for HTTP and it is running like this since a long time.
