### ISSUE TITLE
It is working, but may I reduce the latency?

### ISSUE THREAD

**Issue by AK51** [circuitrocks/ESP32-RTSP#8]
Hi,
I can get the rtsp working. thanks.
I have reduced my rtsp client side latency to almost zero second, but the delay is still about 1 second. 
(FYI, I could make my another IP cam latency close to zero.)
Is there any way I can make the latency close to zero in the server side?
Thanks.

**Comment by hbalasu1** [comment]
how can we reduce the resolution to 320x240 ?

**Comment by beegee-tokyo** [comment]
All of these is in the [Micro-RTSP library](https://github.com/geeksville/Micro-RTSP), not in this code. You need to ask your questions there.

This app is only using the Micro-RTSP library.
